### ISSUE TITLE
Use our custom domain

### ISSUE THREAD

**Issue by justmarkup** [a11yberlin/a11y-meetup-berlin.de#18]
The site is ready now to be published. The last step ist to configure everything so it can be reached under: https://a11y-meetup-berlin.de

@thusslack Could you please enter the DNS records needed for this. See also https://help.github.com/articles/setting-up-an-apex-domain/

Also please make sure that https is enabled by default.

I already added the CNAME here.

Thanks.

**Comment by thusslack** [comment]
The domain is setup; ssl is on its way.

**Comment by thusslack** [comment]
SSL added. https is enforced.
