### ISSUE TITLE
Add email address as a contact option

### ISSUE THREAD

**Issue by justmarkup** [a11yberlin/a11y-meetup-berlin.de#20]
Add a mailto link to info@a11y-meetup-berlin.de in the contact section in the footer.

@josefie Do you have an icon for email, similiar to the one for twitter, meetup, github we can use there?

**Comment by josefie** [comment]
@justmarkup I used this iconset: http://www.iconarchive.com/show/simple-icons-by-danleech.2.html
Unfortunately there is no email icon there, but I can see if I find a different one.

**Comment by justmarkup** [comment]
Thanks @josefie 

Your changes are merged now, so closing this.
