### ISSUE TITLE
Add links to videos and slides from the first edition

### ISSUE THREAD

**Issue by radibit** [a11yberlin/a11y-meetup-berlin.de#24]
Stefan Judis's talk:
- [x] slides
- [x] video

Svenja Heinecke & Sebastian Felix Zappe talk:
- [ ] slides
- [x] video

**Comment by justmarkup** [comment]
Let's wait some more time if we eventually still get the slides from Svenja and Sebastian.

**Comment by justmarkup** [comment]
@radibit Any update regarding the slides. Othwerwise I would suggest we close this issue.

**Comment by radibit** [comment]
@justmarkup I have the link to their slides as they shared it with me when they used my computer for the actual presentation. However, I don't have any approval if we can use it as Sebastian stated that they need to check if that version is ready to be shared. Also I didn't receive any response to my follow up email.

**Comment by justmarkup** [comment]
Closing this now as we still didn't get any feedback.
