### ISSUE TITLE
Submit a talk page

### ISSUE THREAD

**Issue by justmarkup** [a11yberlin/a11y-meetup-berlin.de#7]
For the "Submit a talk" page we need content and a form to submit a talk.

**Comment by radibit** [comment]
I will create a google form with the required fields and will update the button on the website to point to that form.

**Comment by justmarkup** [comment]
We could also use something like https://formspree.io/ and additional we could create a guide how to submit a talk via github issue here and maybe also add an email address so people could send a proposal this way as well. 

Furthermore we should make very clear that we are looking for first-time speakers and speakers from underpresented groups. 

Also, we should write down what we can and want to do help speakers (rehearsal via video chat, offer feedback beforehand...) 

@radibit Could you please also write down what technical equipment is present at the location so speakers can prepare for this?

**Comment by radibit** [comment]
@justmarkup I was thinking for even simpler solution by creating a Gmail account (or connect to our personal ones) and create a google form (many conferences are using this approach).

The goal is to get the minimum required information e.g. person name, talk title, talk abstract, profile pic URL. Then some optional fields like twitter handler, link to slides if the talk has been performed, checkbox if that's a first time appearance as a public speaker (in case an assistance from our side is needed).

Edit: Sorry, closed the issue by mistake 😊 

> @radibit Could you please also write down what technical equipment is present at the location so speakers can prepare for this?

Yup 👍  Will add a paragraph explaining that.
